# Generated by Django 5.2 on 2025-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Table',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('customer_firstName', models.CharField(max_length=100)),
                ('customer_lastName', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100, unique=True)),
                ('customer_phone', models.CharField(max_length=15, unique=True)),
                ('customer_address', models.TextField()),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_state', models.CharField(max_length=50)),
                ('customer_zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
